<template>
  <div id="app-found">
    <VSwitcher :headers="['关注', '推荐']" sticky swipe animated :fixed-top="0">
      <VScroller :throttle="-1" slot="0">
        <p>start</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>关注</p>
        <p>end</p>
      </VScroller>
      <VScroller :throttle="-1" slot="1">
        <p>start</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>推荐</p>
        <p>end</p>
      </VScroller>
    </VSwitcher>
  </div>
</template>

<script>
export default {
  name: 'AppHome',
  layout: 'app',
  components: {},
  props: {},
  data() {
    return {}
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {},
  methods: {}
}
</script>
